### ISSUE TITLE
перевод y700 Lenovo

### ISSUE THREAD

**Issue by vildyaev** [kazhemons/CNtoRU#1]
Приветствую! а возможно ли сделать перевод  китайской версии прошивки для Lenovo y700 не имея планшета на руках, а только ota обновление, хотябы частично, у леново есть еще планшеты, думаю и ним применится, но т.к. популярность устройства гораздо меньше чем Xiaomi, таких модулей не встречал

**Comment by MIUIHELP** [comment]
Сделать можно всё, главное время и желание
